
package principal;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import p1.engine.SimulationResult;
import p1.model.Proceso;
import p1.scheduler.FCFS;
import p1.scheduler.Planificador;
import p1.scheduler.SJF;
import p1.scheduler.SRTF;
import p1.ui.GanttPanel;
import p2.ClockAlgorithm;
import p2.SimulationStep;
import p2.FIFOAlgorithm;
import p2.LRUAlgorithm;
import p2.OptimalAlgorithm;
import p2.PFFAlgorithm;
import p2.PageReplacementAlgorithm;
import p2.SecondChanceAlgorithm;
import p2.VMINAlgorithm;
import p2.WorkingSetAlgorithm;



/**
 *
 * @author RVega
 */


public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private DefaultTableModel modeloTabla;
    private final GanttPanel gantt = new GanttPanel();
    private SimulationResult ultimoResultado;
    private List<Integer> listaPaginas;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        initCustom();
        gantt.setPreferredSize(new Dimension(600, 200));
        listaPaginas = new ArrayList<>();
    }

    private void initCustom() {
    // Modelo de la JTable
    modeloTabla = (DefaultTableModel) tablaProcesos.getModel();

    // Limpia filas nulas generadas por default (si las hay)
    modeloTabla.setRowCount(0);

    // Asegura cabeceras correctas
    if (modeloTabla.getColumnCount() < 3) {
        modeloTabla.setColumnCount(3);
    }
    modeloTabla.setColumnIdentifiers(new Object[]{"ID", "Llegada", "Ráfaga"});

    // Inserta el GanttPanel en el panelGantt que ya tienes en el formulario
    panelGantt.setLayout(new BorderLayout());
    panelGantt.add(gantt, BorderLayout.CENTER);
    panelGantt.revalidate();
    panelGantt.repaint();
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        tiempoLlegada = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cpuBurst = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        quantum = new javax.swing.JTextField();
        tipoAlgoritmo = new javax.swing.JComboBox<>();
        simularRun = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        tablaProcesos = new javax.swing.JTable();
        panelGantt = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRepetir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaResultados = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        quantumActual = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxAlgoritmos = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButtonSubirPaguina = new javax.swing.JButton();
        jButtonRUNRemplazo = new javax.swing.JButton();
        jComboBoxPaguina = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePaguinas = new javax.swing.JTable();
        Paguinas = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelTablaPasoaPaso = new javax.swing.JPanel();
        jPanelResultadosRemplazo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Algoritmo");

        btnAgregar.setText("Agregar Proceso");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel5.setText("Tiempo llegada");

        jLabel6.setText("Rafaga (burst time)");

        jLabel1.setText("Quantum");

        tipoAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RR", "FCFS", "SJF", "SRTF" }));
        tipoAlgoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAlgoritmoActionPerformed(evt);
            }
        });

        simularRun.setBackground(new java.awt.Color(0, 0, 0));
        simularRun.setForeground(new java.awt.Color(255, 255, 255));
        simularRun.setText("RUN");
        simularRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simularRunActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(204, 0, 51));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tiempoLlegada)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cpuBurst)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quantum, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                .addComponent(tipoAlgoritmo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(simularRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tipoAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addComponent(tiempoLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addComponent(cpuBurst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(simularRun)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Llegada", "Ráfaga"
            }
        ));
        jScrollPane.setViewportView(tablaProcesos);

        javax.swing.GroupLayout panelGanttLayout = new javax.swing.GroupLayout(panelGantt);
        panelGantt.setLayout(panelGanttLayout);
        panelGanttLayout.setHorizontalGroup(
            panelGanttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelGanttLayout.setVerticalGroup(
            panelGanttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tabla de procesos");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resultados");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Simulacion");

        jRepetir.setText("Repetir animacion");
        jRepetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRepetirActionPerformed(evt);
            }
        });

        textAreaResultados.setEditable(false);
        textAreaResultados.setBackground(new java.awt.Color(220, 222, 227));
        textAreaResultados.setColumns(20);
        textAreaResultados.setRows(5);
        jScrollPane1.setViewportView(textAreaResultados);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantum:");

        quantumActual.setForeground(new java.awt.Color(255, 255, 255));
        quantumActual.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(quantumActual, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                                .addComponent(panelGantt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRepetir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantumActual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelGantt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRepetir)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addGap(17, 17, 17))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Algoritmos de planificacion", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jComboBoxAlgoritmos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO", "Optimo", "LRU", "Clock", "Second Chance", "VMIN", "Working Set", "PFF" }));
        jComboBoxAlgoritmos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAlgoritmosActionPerformed(evt);
            }
        });

        jLabel9.setText("Algoritmo");

        jButtonSubirPaguina.setText("agregar paguina");
        jButtonSubirPaguina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubirPaguinaActionPerformed(evt);
            }
        });

        jButtonRUNRemplazo.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRUNRemplazo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRUNRemplazo.setText("RUN");
        jButtonRUNRemplazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRUNRemplazoActionPerformed(evt);
            }
        });

        jComboBoxPaguina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabel13.setText("Paguina");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxPaguina, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxAlgoritmos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSubirPaguina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRUNRemplazo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxPaguina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSubirPaguina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRUNRemplazo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTablePaguinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTablePaguinas);

        Paguinas.setForeground(new java.awt.Color(255, 255, 255));
        Paguinas.setText("Paguinas");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Simulacion");

        jPanelTablaPasoaPaso.setEnabled(false);

        javax.swing.GroupLayout jPanelTablaPasoaPasoLayout = new javax.swing.GroupLayout(jPanelTablaPasoaPaso);
        jPanelTablaPasoaPaso.setLayout(jPanelTablaPasoaPasoLayout);
        jPanelTablaPasoaPasoLayout.setHorizontalGroup(
            jPanelTablaPasoaPasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelTablaPasoaPasoLayout.setVerticalGroup(
            jPanelTablaPasoaPasoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelResultadosRemplazoLayout = new javax.swing.GroupLayout(jPanelResultadosRemplazo);
        jPanelResultadosRemplazo.setLayout(jPanelResultadosRemplazoLayout);
        jPanelResultadosRemplazoLayout.setHorizontalGroup(
            jPanelResultadosRemplazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );
        jPanelResultadosRemplazoLayout.setVerticalGroup(
            jPanelResultadosRemplazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Resultados");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Paguinas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelResultadosRemplazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanelTablaPasoaPaso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Paguinas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTablaPasoaPaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelResultadosRemplazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Algoritmos de reemplazo de pagina", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {                                           
//GEN-FIRST:event_btnAgregarActionPerformed
    try {
        String id = "P" + (modeloTabla.getRowCount() + 1);
        int llegada = Integer.parseInt(tiempoLlegada.getText().trim());
        int rafaga  = Integer.parseInt(cpuBurst.getText().trim());
        if (llegada < 0 || rafaga <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Llegada ≥ 0 y Ráfaga > 0");
            return;
        }
        modeloTabla.addRow(new Object[]{id, llegada, rafaga});
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ingresa números válidos en Llegada y Ráfaga.");
    }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    int totalFilas = modeloTabla.getRowCount();
    if (totalFilas > 0) {
        modeloTabla.removeRow(totalFilas - 1); // Elimina la última fila
        // Reetiquetar IDs
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            modeloTabla.setValueAt("P" + (i + 1), i, 0);
        }
    } else {
        JOptionPane.showMessageDialog(this, "No hay procesos para eliminar.");
    }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void simularRunActionPerformed(java.awt.event.ActionEvent evt) {                                           

//GEN-FIRST:event_simularRunActionPerformed
    var procesos = leerProcesosDeTabla();
    if (procesos.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Agrega al menos un proceso.");
        return;
    }

    String algoritmo = String.valueOf(tipoAlgoritmo.getSelectedItem());
    Planificador planificador;

    if ("RR".equals(algoritmo)) {
        try {
            int q = Integer.parseInt(quantum.getText().trim());
            if (q <= 0) throw new NumberFormatException();
            planificador = new p1.schedule.RR(q);
            quantumActual.setText(String.valueOf(q));
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Quantum debe ser un número entero positivo.");
            return;
        }
    } else {
        planificador = crearPlanificador(); // FCFS, SJF, SRTF, etc.
    }

    ultimoResultado = planificador.simular(procesos);
    SimulationResult result = ultimoResultado;
    gantt.animarSegmentos(result.getTimeline());

    // Mostrar métricas en orden de ejecución
    StringBuilder sb = new StringBuilder("=== Métricas ===\n");
    double e = 0, r = 0, tt = 0; int n = 0;
    Set<String> mostrados = new HashSet<>();

    for (var seg : result.getTimeline()) {
        String pid = seg.getProcesoId();
        if ("IDLE".equals(pid) || mostrados.contains(pid)) continue;

        var m = result.getMetricsPorProceso().get(pid);
        sb.append(String.format("%s -> espera=%d, respuesta=%d, turnaround=%d%n",
                pid, m.espera, m.respuesta, m.turnaround));
        e += m.espera; r += m.respuesta; tt += m.turnaround; n++;
        mostrados.add(pid);
    }

    if (n > 0) {
        sb.append(String.format("%nPromedios: espera=%.2f, respuesta=%.2f, turnaround=%.2f", e/n, r/n, tt/n));
    }

    textAreaResultados.setText(sb.toString());
    textAreaResultados.repaint();

    }//GEN-LAST:event_simularRunActionPerformed

    private void tipoAlgoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoAlgoritmoActionPerformed
        // TODO add your handling code here:
    String seleccionado = String.valueOf(tipoAlgoritmo.getSelectedItem());

        if ("RR".equals(seleccionado)) {
            quantum.setEnabled(true);
        } else {
            quantum.setEnabled(false);
        }
    }//GEN-LAST:event_tipoAlgoritmoActionPerformed

    private void jRepetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRepetirActionPerformed
        // TODO add your handling code here:
        
        if (ultimoResultado != null) {
            gantt.animarSegmentos(ultimoResultado.getTimeline());
        } else {
            JOptionPane.showMessageDialog(this, "Primero ejecuta una simulación.");
        }
    }//GEN-LAST:event_jRepetirActionPerformed

    private void jComboBoxAlgoritmosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAlgoritmosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAlgoritmosActionPerformed

    private void jButtonSubirPaguinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubirPaguinaActionPerformed
        
  String seleccion = (String) jComboBoxPaguina.getSelectedItem();

    if (seleccion != null && !seleccion.isEmpty()) {
        try {
            int paginaSeleccionada = Integer.parseInt(seleccion);

            // Inicializar lista si está vacía
            if (listaPaginas == null) {
                listaPaginas = new ArrayList<>();
            }

            // Agregar página a la lista
            listaPaginas.add(paginaSeleccionada);

            // Crear modelo horizontal: una fila, columnas = páginas
            DefaultTableModel model = new DefaultTableModel(1, listaPaginas.size());
            String[] columnas = listaPaginas.stream()
                                            .map(String::valueOf)
                                            .toArray(String[]::new);
            model.setColumnIdentifiers(columnas);
            model.setValueAt("", 0, 0); // fila vacía
            jTablePaguinas.setModel(model);

            // Ajustar tamaño para evitar espacio gris
            jTablePaguinas.setRowHeight(35);
            jTablePaguinas.setPreferredScrollableViewportSize(
                new Dimension(jTablePaguinas.getPreferredSize().width, 40)
            );
            jScrollPane2.setPreferredSize(new Dimension(jPanelTablaPasoaPaso.getWidth(), 50));

            // Renderer para encabezados en azul
            jTablePaguinas.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value,
                        boolean isSelected, boolean hasFocus, int row, int column) {
                    JLabel header = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    header.setForeground(Color.BLUE);
                    header.setFont(new Font("Arial", Font.BOLD, 14));
                    header.setHorizontalAlignment(SwingConstants.CENTER);
                    return header;
                }
            });

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error: valor no numérico.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona una página válida.");
    }
    }//GEN-LAST:event_jButtonSubirPaguinaActionPerformed

    private void jButtonRUNRemplazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRUNRemplazoActionPerformed
    
    try {
        // Pedir número de marcos
        String input = JOptionPane.showInputDialog(this, "Ingrese el número de marcos:", "Configuración", JOptionPane.QUESTION_MESSAGE);
        if (input == null || input.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un valor.");
            return;
        }
        int frames = Integer.parseInt(input);

        // Obtener algoritmo seleccionado
        String algoritmoSeleccionado = (String) jComboBoxAlgoritmos.getSelectedItem();
        PageReplacementAlgorithm algoritmo;

    switch (algoritmoSeleccionado) {
        case "FIFO": algoritmo = new FIFOAlgorithm(frames); break;
        case "Optimo": algoritmo = new OptimalAlgorithm(frames, listaPaginas); break;
        case "LRU": algoritmo = new LRUAlgorithm(frames); break;
        case "Clock":algoritmo = new ClockAlgorithm(frames);break;
        case "Second Chance": algoritmo = new SecondChanceAlgorithm(frames);break;
        case "VMIN": int windowSize = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese tamaño de ventana:", "Configuración", JOptionPane.QUESTION_MESSAGE));algoritmo = new VMINAlgorithm(frames, listaPaginas, windowSize);break;
        case "Working Set": int delta = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese tamaño de ventana (Δ):", "Configuración", JOptionPane.QUESTION_MESSAGE)); algoritmo = new WorkingSetAlgorithm(frames, delta);break;
        case "PFF":
        int initialFrames = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese marcos iniciales:"));
        int minFrames = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese marcos mínimos:"));
        int maxFrames = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese marcos máximos:"));
        double lowerThreshold = Double.parseDouble(JOptionPane.showInputDialog(this, "Ingrese umbral inferior (ej. 0.2):"));
        double upperThreshold = Double.parseDouble(JOptionPane.showInputDialog(this, "Ingrese umbral superior (ej. 0.5):"));
        algoritmo = new PFFAlgorithm(initialFrames, minFrames, maxFrames, lowerThreshold, upperThreshold);
        break;
        
        
        default: JOptionPane.showMessageDialog(this, "Selecciona un algoritmo válido."); return;
    }
        // Ejecutar simulación
            p2.SimulatorController controller = new p2.SimulatorController();
        List<p2.SimulationStep> pasos = controller.runSimulation(listaPaginas, algoritmo);

        // Mostrar resultados en la tabla y panel
        mostrarResultados(pasos, frames, algoritmo.getPageFaults());

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Número inválido.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al ejecutar la simulación: " + ex.getMessage());
    }
        
        
        
        
    }//GEN-LAST:event_jButtonRUNRemplazoActionPerformed
    
    
private List<Proceso> leerProcesosDeTabla() {
    List<Proceso> lista = new ArrayList<>();
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        String id = String.valueOf(modeloTabla.getValueAt(i, 0));
        int llegada = Integer.parseInt(String.valueOf(modeloTabla.getValueAt(i, 1)));
        int rafaga  = Integer.parseInt(String.valueOf(modeloTabla.getValueAt(i, 2)));
        lista.add(new Proceso(id, llegada, rafaga));
    }
    return lista;
}


private Planificador crearPlanificador() {
    String alg = String.valueOf(tipoAlgoritmo.getSelectedItem());
    switch (alg) {
        case "FCFS": return new FCFS();
        case "SJF":  return new SJF();
        case "SRTF": return new SRTF();
        default: return new FCFS();
    }
}
//=====Mostrar resultado========================================
    private void mostrarResultados(List<SimulationStep> pasos, int frames, int pageFaults) {
    DefaultTableModel model = new DefaultTableModel();

    // Columnas = páginas
    for (SimulationStep step : pasos) {
        model.addColumn(String.valueOf(step.getPage()));
    }

    // Filas = marcos
    for (int i = 0; i < frames; i++) {
        model.addRow(new Object[pasos.size()]);
    }

    // Inicializar matriz con "-"
    for (int row = 0; row < frames; row++) {
        for (int col = 0; col < pasos.size(); col++) {
            model.setValueAt("-", row, col);
        }
    }

    // Llenar la tabla paso a paso
    List<Integer[]> previousState = new ArrayList<>();
    for (int i = 0; i < frames; i++) {
        previousState.add(new Integer[pasos.size()]);
    }

    for (int col = 0; col < pasos.size(); col++) {
        List<Integer> estado = pasos.get(col).getMemoryState();
        Integer replacedIndex = pasos.get(col).getReplacedIndex();

        for (int row = 0; row < frames; row++) {
            String valor = (estado.get(row) != null) ? String.valueOf(estado.get(row)) : "-";

            // Si no cambió respecto al paso anterior, deja el valor anterior
            if (col > 0 && previousState.get(row)[col - 1] != null && previousState.get(row)[col - 1].equals(estado.get(row))) {
                valor = String.valueOf(previousState.get(row)[col - 1]);
            }

            // Guardar estado actual
            previousState.get(row)[col] = estado.get(row);

            // Marcar reemplazo
            if (replacedIndex != null && row == replacedIndex) {
                valor += "*";
            }

            model.setValueAt(valor, row, col);
        }
    }

    JTable tabla = new JTable(model);
    tabla.setRowHeight(35);

    // Renderer para colorear reemplazos
    tabla.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            String val = (value != null) ? value.toString() : "";
            if (val.endsWith("*")) {
                c.setBackground(Color.RED);
                c.setForeground(Color.WHITE);
                setText(val.replace("*", ""));
            } else {
                c.setBackground(Color.WHITE);
                c.setForeground(Color.BLACK);
            }
            setHorizontalAlignment(SwingConstants.CENTER);
            return c;
        }
    });

    JScrollPane scroll = new JScrollPane(tabla);
    scroll.setPreferredSize(new Dimension(jPanelTablaPasoaPaso.getWidth(), frames * 40));
    jPanelTablaPasoaPaso.removeAll();
    jPanelTablaPasoaPaso.setLayout(new BorderLayout());
    jPanelTablaPasoaPaso.add(scroll, BorderLayout.CENTER);
    jPanelTablaPasoaPaso.revalidate();
    jPanelTablaPasoaPaso.repaint();

    // Mostrar métricas
    int total = pasos.size();
    int aciertos = total - pageFaults;
    double tasa = (aciertos * 100.0) / total;
    jPanelResultadosRemplazo.removeAll();
    jPanelResultadosRemplazo.setLayout(new GridLayout(3, 1));
    jPanelResultadosRemplazo.setPreferredSize(new Dimension(jPanelTablaPasoaPaso.getWidth(), 100));
    JLabel lblAciertos = new JLabel("Número de aciertos: " + aciertos);
    lblAciertos.setForeground(Color.GREEN);
    lblAciertos.setFont(new Font("Arial", Font.BOLD, 14));
    JLabel lblFallos = new JLabel("Fallos de página: " + pageFaults);
    lblFallos.setForeground(Color.RED);
    lblFallos.setFont(new Font("Arial", Font.BOLD, 14));
    JLabel lblTasa = new JLabel(String.format("Tasa de acierto: %.2f%%", tasa));
    lblTasa.setFont(new Font("Arial", Font.BOLD, 14));
    jPanelResultadosRemplazo.add(lblAciertos);
    jPanelResultadosRemplazo.add(lblFallos);
    jPanelResultadosRemplazo.add(lblTasa);
    jPanelResultadosRemplazo.revalidate();
    jPanelResultadosRemplazo.repaint();
}
//=====Mostrar resultado Fin=====================================
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Paguinas;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JTextField cpuBurst;
    private javax.swing.JButton jButtonRUNRemplazo;
    private javax.swing.JButton jButtonSubirPaguina;
    private javax.swing.JComboBox<String> jComboBoxAlgoritmos;
    private javax.swing.JComboBox<String> jComboBoxPaguina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelResultadosRemplazo;
    private javax.swing.JPanel jPanelTablaPasoaPaso;
    private javax.swing.JButton jRepetir;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTablePaguinas;
    private javax.swing.JPanel panelGantt;
    private javax.swing.JTextField quantum;
    private javax.swing.JLabel quantumActual;
    private javax.swing.JButton simularRun;
    private javax.swing.JTable tablaProcesos;
    private javax.swing.JTextArea textAreaResultados;
    private javax.swing.JTextField tiempoLlegada;
    private javax.swing.JComboBox<String> tipoAlgoritmo;
    // End of variables declaration//GEN-END:variables


}
